[package]
name = "ocb_sys"
version = "0.0.1"
authors = []
build = "build.rs"

[lib]
name = "ocb_sys"
path = "lib.rs"

[build-dependencies]
cc = "1"
libc = "0.2"

[dependencies]
openssl-sys = "0.9"
libc = "0.2"
